# Generated by Django 4.2 on 2023-04-09 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_payment_orderplaced'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='status',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
